//! Day 5 Hour 1 -- property-based tests. Every crate's own `tests/`
//! directory already covers specific examples (a signature that fails, a
//! nonce that's stale, a log that gets truncated); these tests instead
//! encode invariants that must hold for *any* input drawn from a
//! structured domain, and let `proptest` search that domain for a
//! counterexample.
//!
//! "Structured" is the operative word -- every generator below draws from
//! a small, meaningful domain (a fixed pool of participant accounts,
//! balances in a realistic range, nonce sequences that are either exactly
//! correct or deliberately stale/ahead), never raw `any::<[u8; 32]>()`
//! noise. A `SenderMissing` or `InvalidSignature` rejection on every single
//! run would make a property test pass for the wrong reason -- these
//! generators are built so the interesting paths (affordable transfers,
//! nonce collisions between two transactions from the same sender,
//! deliberately stale/future nonces) are actually reachable.

use block::block::{Block, BlockHeader};
use block::{GENESIS_PARENT_HASH, merkle_root};
use chain::Chain;
use execution::{GenesisConfig, replay_chain};
use mempool::pool::{PoolAdmission, TransactionPool};
use primitives::amount::checked_add_amount;
use primitives::{AccountId, Amount, BASE_FEE, Nonce};
use proptest::prelude::*;
use state::chain_state::ChainState;
use storage::{AppendOnlyBlockStore, BlockStore};
use transaction::transaction::{SignedTransaction, UnsignedTransaction};

/// Fixed pool of participant accounts every property test draws from.
/// Picking indices into a small, shared pool (rather than generating
/// arbitrary 32-byte arrays) makes the interesting case -- two generated
/// transactions sharing a sender -- a common, reachable outcome instead of
/// a one-in-2^256 accident.
const PARTICIPANTS: [u8; 4] = [1, 2, 3, 4];
const FEE_COLLECTOR: u8 = 99;

fn account_id(byte: u8) -> AccountId {
    [byte; 32]
}

fn participant_index_strategy() -> impl Strategy<Value = usize> {
    0..PARTICIPANTS.len()
}

/// A starting balance comfortably larger than any amount `amount_strategy`
/// can produce, so "insufficient balance" is never an accident of the
/// ranges chosen -- only ever a deliberate part of a test (see
/// `proptest_failed_transactions_do_not_mutate_state`).
fn balance_strategy() -> impl Strategy<Value = Amount> {
    1_000..1_000_000u64
}

fn amount_strategy() -> impl Strategy<Value = Amount> {
    1..500u64
}

/// `(sender index, receiver offset, raw amount)`. `receiver offset` is
/// resolved mod `PARTICIPANTS.len() - 1` and added to `sender index + 1`,
/// so the receiver is always a *different* participant by construction --
/// `SenderEqualsReceiver` is never generated by accident.
fn intent_strategy() -> impl Strategy<Value = (usize, usize, u64)> {
    (participant_index_strategy(), 0..(PARTICIPANTS.len() - 1), 0..1000u64)
}

fn resolve_receiver(sender_idx: usize, receiver_offset: usize) -> usize {
    (sender_idx + 1 + receiver_offset) % PARTICIPANTS.len()
}

/// Clamps a raw generated amount into a small, always-affordable range
/// (paired with `balance_strategy`'s minimum of 1,000).
fn resolve_amount(raw: u64) -> Amount {
    1 + (raw % 50)
}

fn genesis_config(initial_balance: Amount) -> GenesisConfig {
    let fee_collector = account_id(FEE_COLLECTOR);
    let accounts = PARTICIPANTS
        .iter()
        .map(|&byte| (account_id(byte), initial_balance))
        .chain(std::iter::once((fee_collector, 0)))
        .collect();
    GenesisConfig::new(accounts, fee_collector)
}

fn genesis_state(initial_balance: Amount) -> ChainState {
    genesis_config(initial_balance).build_state()
}

fn signed_transfer(from: AccountId, to: AccountId, amount: Amount, nonce: Nonce) -> SignedTransaction {
    SignedTransaction::sign(UnsignedTransaction { from, to, amount, nonce })
}

/// True if `amount + BASE_FEE` is actually payable out of `balance` --
/// mirrors the exact check `apply_signed_transaction` and
/// `TransactionPool::submit_transaction` both make (docs/fee-model.md).
fn is_affordable(amount: Amount, balance: Amount) -> bool {
    checked_add_amount(amount, BASE_FEE)
        .map(|required| required <= balance)
        .unwrap_or(false)
}

/// Builds a block chaining onto `parent_header` (or genesis, if `None`),
/// computing its transaction root and state commitment from actually
/// applying `transactions` to `parent_state` -- the same construction
/// `crates/chain/tests/restart.rs` and `crates/node/src/commands.rs` use.
/// Requires `transactions` to already be individually valid and
/// nonce-ordered against `parent_state`; that's the caller's job.
fn build_block(
    parent_state: &ChainState,
    parent_header: Option<&BlockHeader>,
    transactions: Vec<SignedTransaction>,
) -> Block {
    let root = merkle_root(
        &transactions
            .iter()
            .map(|tx| tx.transaction.id())
            .collect::<Vec<_>>(),
    );

    let mut expected_state = parent_state.clone();
    for tx in &transactions {
        expected_state
            .apply_signed_transaction(tx.clone())
            .expect("build_block is only ever given individually valid, nonce-ordered transactions");
    }

    let (height, parent_hash) = match parent_header {
        None => (0, GENESIS_PARENT_HASH),
        Some(header) => (header.height + 1, header.block_hash),
    };

    Block {
        header: BlockHeader::new(height, parent_hash, root, expected_state.state_commitment(), [9u8; 32], height),
        transactions,
    }
}

#[derive(Debug, Clone, Copy)]
enum NonceCase {
    /// Exactly the sender's next expected nonce.
    Correct,
    /// One less than expected -- a nonce already spent.
    Stale,
    /// Two more than expected -- a nonce with a gap before it.
    FutureGap,
}

fn nonce_case_strategy() -> impl Strategy<Value = NonceCase> {
    prop_oneof![
        Just(NonceCase::Correct),
        Just(NonceCase::Stale),
        Just(NonceCase::FutureGap),
    ]
}

/// `0..=3` transactions per block, `1..=4` blocks -- small enough that
/// `proptest`'s shrinker stays useful, large enough to exercise multiple
/// senders and multiple blocks chaining onto each other.
fn chain_intents_strategy() -> impl Strategy<Value = Vec<Vec<(usize, usize, u64)>>> {
    prop::collection::vec(prop::collection::vec(intent_strategy(), 0..=3), 1..=4)
}

proptest! {
    #![proptest_config(ProptestConfig::with_cases(64))]

    /// A well-formed, affordable transfer moves value between two existing
    /// accounts but never creates or destroys it. In this codebase's fee
    /// model the fee is credited to the fee collector, not burned
    /// (docs/fee-model.md) -- so total supply isn't merely "preserved
    /// except fees", it is conserved exactly.
    #[test]
    fn proptest_valid_transfers_preserve_supply(
        initial_balance in balance_strategy(),
        sender_idx in participant_index_strategy(),
        receiver_offset in 0..(PARTICIPANTS.len() - 1),
        raw_amount in amount_strategy(),
    ) {
        let receiver_idx = resolve_receiver(sender_idx, receiver_offset);
        let from = account_id(PARTICIPANTS[sender_idx]);
        let to = account_id(PARTICIPANTS[receiver_idx]);
        let amount = resolve_amount(raw_amount);
        prop_assume!(is_affordable(amount, initial_balance));

        let state = genesis_state(initial_balance);
        let supply_before = state.total_supply();

        let mut next_state = state.clone();
        next_state
            .apply_signed_transaction(signed_transfer(from, to, amount, 0))
            .expect("well-formed, affordable transfer must succeed");

        prop_assert_eq!(next_state.total_supply(), supply_before);
    }

    /// Whatever the reason a transaction fails execution for (stale nonce,
    /// a nonce gap, an unaffordable amount), `apply_signed_transaction`
    /// must leave state byte-for-byte as it found it --
    /// docs/architecture.md's "Failures should not leave partial state
    /// changes behind", checked directly rather than trusted.
    #[test]
    fn proptest_failed_transactions_do_not_mutate_state(
        initial_balance in balance_strategy(),
        sender_idx in participant_index_strategy(),
        receiver_offset in 0..(PARTICIPANTS.len() - 1),
        raw_amount in amount_strategy(),
        nonce_case in nonce_case_strategy(),
        advance_first in any::<bool>(),
    ) {
        let receiver_idx = resolve_receiver(sender_idx, receiver_offset);
        let from = account_id(PARTICIPANTS[sender_idx]);
        let to = account_id(PARTICIPANTS[receiver_idx]);
        let amount = resolve_amount(raw_amount);

        let mut state = genesis_state(initial_balance);

        // Optionally spend nonce 0 first, so "stale nonce" (reusing a
        // nonce that's already been spent) is reachable, not degenerate.
        if advance_first {
            state
                .apply_signed_transaction(signed_transfer(from, to, 1, 0))
                .expect("small warm-up transfer must be affordable and valid");
        }

        let expected_nonce = state.get_account(&from).unwrap().nonce;
        let nonce = match nonce_case {
            NonceCase::Correct => expected_nonce,
            NonceCase::Stale => {
                prop_assume!(expected_nonce > 0);
                expected_nonce - 1
            }
            NonceCase::FutureGap => expected_nonce + 2,
        };

        let before = state.clone();
        let mut candidate = state.clone();
        let result = candidate.apply_signed_transaction(signed_transfer(from, to, amount, nonce));

        if result.is_err() {
            prop_assert_eq!(candidate, before);
        }
    }

    /// Replaying a block sequence from genesis (`execution::replay_chain`)
    /// must reproduce exactly the state root that executing those same
    /// blocks live, one at a time, already produced -- docs/replay.md's
    /// core rule, checked over generated multi-block, multi-sender
    /// sequences rather than one hand-picked example.
    #[test]
    fn proptest_replay_matches_original_state(
        initial_balance in balance_strategy(),
        chain_intents in chain_intents_strategy(),
    ) {
        let mut state = genesis_state(initial_balance);
        let mut nonces = [0u64; PARTICIPANTS.len()];
        let mut blocks: Vec<Block> = Vec::new();

        for block_intents in chain_intents {
            let mut nonce_cursor = nonces;
            let mut transactions = Vec::new();
            for (sender_idx, receiver_offset, raw_amount) in block_intents {
                let receiver_idx = resolve_receiver(sender_idx, receiver_offset);
                let from = account_id(PARTICIPANTS[sender_idx]);
                let to = account_id(PARTICIPANTS[receiver_idx]);
                let amount = resolve_amount(raw_amount);
                let nonce = nonce_cursor[sender_idx];
                nonce_cursor[sender_idx] += 1;
                transactions.push(signed_transfer(from, to, amount, nonce));
            }

            let block = build_block(&state, state.tip(), transactions);
            state = ChainState::execute_block(&state, block.clone())
                .expect("build_block only ever produces a structurally valid, affordable block");
            nonces = nonce_cursor;
            blocks.push(block);
        }

        let replay_result = replay_chain(genesis_config(initial_balance), &blocks)
            .expect("every block in `blocks` already executed successfully once");

        prop_assert_eq!(replay_result.final_state_root, state.state_commitment());
        prop_assert_eq!(replay_result.tip_hash, state.tip().map(|header| header.block_hash));
        prop_assert_eq!(replay_result.height, state.tip().map(|header| header.height));
        prop_assert_eq!(replay_result.blocks_replayed, blocks.len());
    }

    /// `TransactionPool` orders transactions by `(AccountId, Nonce)`
    /// (`ordered_transactions`), not by insertion order. Submitting the
    /// same generated transactions to two pools in reverse order of each
    /// other must produce the same resulting order.
    #[test]
    fn proptest_mempool_ordering_is_deterministic(
        initial_balance in balance_strategy(),
        intents in prop::collection::vec(intent_strategy(), 1..10),
    ) {
        let state = genesis_state(initial_balance);
        let mut nonce_cursor = [0u64; PARTICIPANTS.len()];
        let mut txs = Vec::new();
        for (sender_idx, receiver_offset, raw_amount) in intents {
            let receiver_idx = resolve_receiver(sender_idx, receiver_offset);
            let from = account_id(PARTICIPANTS[sender_idx]);
            let to = account_id(PARTICIPANTS[receiver_idx]);
            let amount = resolve_amount(raw_amount);
            let nonce = nonce_cursor[sender_idx];
            nonce_cursor[sender_idx] += 1;
            txs.push(signed_transfer(from, to, amount, nonce));
        }

        let mut pool_forward = TransactionPool::new();
        for tx in txs.iter().cloned() {
            pool_forward.submit_transaction(tx, &state);
        }

        let mut pool_reversed = TransactionPool::new();
        for tx in txs.iter().rev().cloned() {
            pool_reversed.submit_transaction(tx, &state);
        }

        let forward_ids: Vec<_> = pool_forward
            .ordered_transactions()
            .iter()
            .map(|tx| tx.transaction.id())
            .collect();
        let reversed_ids: Vec<_> = pool_reversed
            .ordered_transactions()
            .iter()
            .map(|tx| tx.transaction.id())
            .collect();

        prop_assert_eq!(forward_ids, reversed_ids);
    }

    /// Submitting the exact same transaction twice must never double-admit
    /// it: the second submission is always `Duplicate`, and the pool's
    /// size never reflects it twice.
    #[test]
    fn proptest_duplicate_transaction_ids_never_accepted_twice(
        initial_balance in balance_strategy(),
        sender_idx in participant_index_strategy(),
        receiver_offset in 0..(PARTICIPANTS.len() - 1),
        raw_amount in amount_strategy(),
    ) {
        let receiver_idx = resolve_receiver(sender_idx, receiver_offset);
        let from = account_id(PARTICIPANTS[sender_idx]);
        let to = account_id(PARTICIPANTS[receiver_idx]);
        let amount = resolve_amount(raw_amount);
        prop_assume!(is_affordable(amount, initial_balance));

        let state = genesis_state(initial_balance);
        let tx = signed_transfer(from, to, amount, 0);

        let mut pool = TransactionPool::new();
        let first = pool.submit_transaction(tx.clone(), &state);
        let second = pool.submit_transaction(tx, &state);

        prop_assert_eq!(first, PoolAdmission::Accepted);
        prop_assert_eq!(second, PoolAdmission::Duplicate);
        prop_assert_eq!(pool.len(), 1);
    }

    /// Re-importing a block that's already canonical must be a safe
    /// no-op, not a second application of its effects: `Chain::import_block`
    /// rejects it (its `parent_hash` no longer matches the tip once the
    /// first import already advanced past it -- docs/block-validation.md),
    /// and both canonical state and durable storage are left exactly as
    /// the first import left them.
    #[test]
    fn proptest_block_import_is_idempotent(
        initial_balance in balance_strategy(),
        sender_idx in participant_index_strategy(),
        receiver_offset in 0..(PARTICIPANTS.len() - 1),
        raw_amount in amount_strategy(),
    ) {
        let receiver_idx = resolve_receiver(sender_idx, receiver_offset);
        let from = account_id(PARTICIPANTS[sender_idx]);
        let to = account_id(PARTICIPANTS[receiver_idx]);
        let amount = resolve_amount(raw_amount);
        prop_assume!(is_affordable(amount, initial_balance));

        let dir = tempfile::tempdir().expect("tempdir");
        let store = AppendOnlyBlockStore::open(dir.path().join("blocks.log")).expect("open store");
        let mut chain = Chain::new(genesis_state(initial_balance), store);

        let block = build_block(chain.state(), None, vec![signed_transfer(from, to, amount, 0)]);

        chain.import_block(block.clone()).expect("first import of a valid block must succeed");
        let state_after_first = chain.state().clone();
        let records_after_first = chain.store().load_blocks().expect("load blocks").len();

        let second_result = chain.import_block(block);

        prop_assert!(second_result.is_err());
        prop_assert_eq!(chain.state(), &state_after_first);
        prop_assert_eq!(chain.store().load_blocks().expect("load blocks").len(), records_after_first);
    }
}
